<?php
declare(strict_types=1);
namespace App\Services;
use PDO;

final class PurchaseService
{
    public function __construct(private readonly PDO $database, private readonly NextcloudStorage $storage) {}
    private function manager(array $session): void { if (($session['role'] ?? '') !== 'director' || ($session['subrole'] ?? '') !== 'administrativo') throw new \DomainException('No autorizado.'); }
    private function slug(string $value): string { $value = iconv('UTF-8', 'ASCII//TRANSLIT//IGNORE', trim($value)) ?: trim($value); $value = strtolower($value); return trim((string) preg_replace('/[^a-z0-9]+/', '_', $value), '_'); }
    private function folderName(string $slug, array $user): string { return $slug . '_' . $this->slug((string) ($user['last_name'] ?? '')) . '_' . $this->slug((string) ($user['name'] ?? '')); }
    public function users(array $session, string $role, string $query): array { $this->manager($session); $query = '%' . $query . '%'; $statement = $this->database->prepare('SELECT id, username, name, last_name, role, subrole FROM users WHERE is_active=1 AND (role=? OR subrole=?) AND (name LIKE ? OR last_name LIKE ? OR username LIKE ?) ORDER BY name LIMIT 30'); $statement->execute([$role, $role, $query, $query, $query]); return ['users' => $statement->fetchAll(PDO::FETCH_ASSOC)]; }
    public function list(array $session): array { $this->manager($session); $statement = $this->database->query('SELECT p.id,p.name,p.slug,p.is_active,p.created_at,u.id AS delegated_user_id,u.name AS delegated_name,u.last_name AS delegated_last_name,u.role,u.subrole FROM public_purchases p INNER JOIN users u ON u.id=p.delegated_user_id ORDER BY p.created_at DESC'); $purchases = $statement->fetchAll(PDO::FETCH_ASSOC); foreach ($purchases as &$purchase) { $purchase['folder'] = $purchase['slug'] . '_' . $this->slug((string) $purchase['delegated_last_name']) . '_' . $this->slug((string) $purchase['delegated_name']); } unset($purchase); return ['purchases' => $purchases]; }
    public function create(array $payload, array $session): array { $this->manager($session); $name = trim((string) ($payload['name'] ?? '')); $userId = (int) ($payload['user_id'] ?? 0); $slug = $this->slug($name); if ($name === '' || $slug === '' || $userId < 1) throw new \InvalidArgumentException('Ingrese el nombre y el usuario delegado.'); $user = $this->findUser($userId); if ($user === null) throw new \InvalidArgumentException('Usuario delegado no válido.'); $folder = $this->folderName($slug, $user); if (!$this->storage->ensureDirectory('documentos', 'procesos/' . $folder)) throw new \RuntimeException('No se pudo crear la carpeta de la compra.'); $statement = $this->database->prepare('INSERT INTO public_purchases (name,slug,delegated_user_id,delegated_by) VALUES (?,?,?,?)'); $statement->execute([$name, $slug, $userId, (int) $session['sub']]); return ['message' => 'Compra delegada a ' . trim($user['name'] . ' ' . $user['last_name']) . ' con éxito.']; }
    public function update(int $id, array $payload, array $session): array { $this->manager($session); $name = trim((string) ($payload['name'] ?? '')); $slug = $this->slug($name); if ($name === '' || $slug === '') throw new \InvalidArgumentException('Nombre de compra inválido.'); $statement = $this->database->prepare('UPDATE public_purchases SET name=?,slug=? WHERE id=?'); $statement->execute([$name, $slug, $id]); return ['ok' => true]; }
    public function deactivate(int $id, array $session): array { $this->manager($session); $this->database->prepare('UPDATE public_purchases SET is_active=0 WHERE id=?')->execute([$id]); return ['ok' => true]; }
    private function findUser(int $id): ?array { $statement = $this->database->prepare('SELECT id,name,last_name FROM users WHERE id=? AND is_active=1'); $statement->execute([$id]); return $statement->fetch(PDO::FETCH_ASSOC) ?: null; }
}
